apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: app
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/component: grpc
    app.kubernetes.io/part-of: microservices-grpc-kubernetes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory-service
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc

