apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - catalog-deployment.yaml
  - catalog-service.yaml
  - inventory-deployment.yaml
  - inventory-service.yaml
