apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-no-resources-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-no-resources-demo
  template:
    metadata:
      labels:
        app: bad-no-resources-demo
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: ghcr.io/vladfcs/golang-microservice-university-gateway-service:sha-e98a03f
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
