apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsigned-image-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unsigned-image-demo
  template:
    metadata:
      labels:
        app: unsigned-image-demo
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: ghcr.io/vladfcs/golang-microservice-university-gateway-service:unsigned-demo
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
