apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: microservices-grpc-kubernetes
spec:
  project: default
  source:
    repoURL: https://github.com/VladFCS/golang-microservice-university.git
    targetRevision: main
    path: deploy/gitops/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: microservices-grpc-kubernetes
