apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-no-limits
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-no-limits
  template:
    metadata:
      labels:
        app: demo-no-limits
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: ghcr.io/vladfcs/golang-microservice-university-gateway-service:v1.0.0
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

