apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-unsigned
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-unsigned
  template:
    metadata:
      labels:
        app: demo-unsigned
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: nginx:1.27.4
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

