// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type InventoryStock struct {
	ProductID string
	Available int64
	Reserved  int64
}

type Product struct {
	ID          string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
}
