// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price_cents, currency
FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
	)
	return i, err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (
    id,
    name,
    description,
    price_cents,
    currency
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price_cents = EXCLUDED.price_cents,
    currency = EXCLUDED.currency
RETURNING id, name, description, price_cents, currency
`

type UpsertProductParams struct {
	ID          string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
	)
	return i, err
}
