// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const getStockByProductID = `-- name: GetStockByProductID :one
SELECT product_id, available, reserved
FROM inventory_stocks
WHERE product_id = $1
LIMIT 1
`

func (q *Queries) GetStockByProductID(ctx context.Context, productID string) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, getStockByProductID, productID)
	var i InventoryStock
	err := row.Scan(&i.ProductID, &i.Available, &i.Reserved)
	return i, err
}

const reserveStock = `-- name: ReserveStock :one
UPDATE inventory_stocks
SET
    available = available - $2,
    reserved = reserved + $2
WHERE product_id = $1
  AND available >= $2
RETURNING product_id, available, reserved
`

type ReserveStockParams struct {
	ProductID string
	Available int64
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, reserveStock, arg.ProductID, arg.Available)
	var i InventoryStock
	err := row.Scan(&i.ProductID, &i.Available, &i.Reserved)
	return i, err
}

const upsertStock = `-- name: UpsertStock :one
INSERT INTO inventory_stocks (
    product_id,
    available,
    reserved
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (product_id) DO UPDATE
SET
    available = EXCLUDED.available,
    reserved = EXCLUDED.reserved
RETURNING product_id, available, reserved
`

type UpsertStockParams struct {
	ProductID string
	Available int64
	Reserved  int64
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, upsertStock, arg.ProductID, arg.Available, arg.Reserved)
	var i InventoryStock
	err := row.Scan(&i.ProductID, &i.Available, &i.Reserved)
	return i, err
}
